# Generated by Django 4.2.5 on 2023-10-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cartitem_price_remove_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
        ),
        migrations.DeleteModel(
            name='CartOrderProduct',
        ),
    ]
