# Generated by Django 4.2.5 on 2023-10-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cartorderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderproduct',
            name='product_status',
        ),
    ]
