# Generated by Django 4.2.5 on 2023-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_cartorderproduct_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderproduct',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
