# Generated by Django 4.2.5 on 2023-10-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cartorderproduct_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderproduct',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='invoice_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=999999, null=True),
        ),
    ]
