# Generated by Django 4.2.5 on 2023-10-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cartorderproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartorderproduct',
            name='user',
        ),
    ]
