# Generated by Django 4.2 on 2023-10-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
