# Generated by Django 4.2 on 2023-10-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cartorder_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
