# Generated by Django 4.2 on 2023-10-23 07:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_rename_locality_customer_address_customer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Address',
        ),
    ]
