# Generated by Django 4.2 on 2023-10-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
