# Generated by Django 4.2 on 2023-10-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_wishlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
