# Generated by Django 4.2 on 2023-10-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cartorder_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='address',
        ),
    ]
