# Generated by Django 4.2 on 2023-11-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_cartorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
